<h1><center>Laboratorio 3: El Pandas no muerde (act. I) 🐼</center></h1>

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos</strong></center>

---

### Cuerpo Docente

- Profesores: Pablo Badilla y Diego Cortez
- Auxiliares: Valentina Rojas y Melanie Peña
- Ayudantes: Javiera Arévalo, Tamara Carrasco y Ignacio Reyes


### Equipo: SUPER IMPORTANTE - notebooks sin nombre no serán revisados

- Nombre de alumno 1: Javiera Yáñez Sánchez


---

### Reglas

- **Grupos de 2 personas**
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Prohibido copiar.
- Uso de LLM (Copilot, Claude, Antigravity, Cursor, etc.) restringido a consultas, documentación y corrección de errores. 

### Objetivos

- Entender, aplicar y aprovechar las ventajas que nos ofrece la libreria `pandas` para manejar datos tabulares.
- Aprender a utilizar la documentación de pandas (y en general, de cualquier librería de python) como también a buscar soluciones en la web.

> ⚠️ **Importante**: El laboratorio deberá ser desarrollado sin el uso de iteradores nativos de python (aka "for", "while"). La idea es que aprendan a exprimir al máximo las funciones optimizadas que nos entrega `pandas`.

### Librerias utiles para el Lab 😸

In [3]:
!uv pip install pandas plotly

Using Python 3.14.2 environment at: /Users/javierayanez/Documents/Semestre 11/MDS7202-Laboratorio_Programacion_Cientifica/MDS7202/.venv
Audited 2 packages in 53ms


In [4]:
import pandas as pd
import plotly.express as px

Exception ignored in PyObject_HasAttr(); consider using PyObject_HasAttrWithError(), PyObject_GetOptionalAttr() or PyObject_GetAttr():
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
AttributeError: partially initialized module 'pandas' from '/Users/javierayanez/Documents/Semestre 11/MDS7202-Laboratorio_Programacion_Cientifica/Studio J - MDS7202/.venv/lib/python3.14/site-packages/pandas/__init__.py' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)


---

# 1. Rendimiento en Estudiantes 📚

### 📊 Sobre los datos

El objetivo principal será realizar un trabajo de limpieza y preparación de datos utilizando exclusivamente DataFrames y las herramientas asociadas a estos. 

Para esto deberán trabajar con el dataset `students_grades.json`, el cual pueden descargar desde la siguiente URL:

> https://raw.githubusercontent.com/MDS7202/MDS7202/refs/heads/main/recursos/2026-01/labs/lab3/students_grades.json

El dataset contiene información sobre el rendimiento de alumnos en distintos ramos. Cada fila representa un estudiante con las siguientes columnas:

- `names`: Nombre del estudiante
- `gender`: Género
- `race/ethnicity`: Grupo étnico
- `parental level of education`: Nivel educacional de los padres
- `lunch`: Tipo de almuerzo (estándar o reducido)
- `test preparation course`: Si completó curso de preparación
- `math score`: Nota de matemáticas (escala 0-100)
- `reading score`: Nota de lectura (escala 0-100)
- `writing score`: Nota de escritura (escala 0-100)


**Nota sobre GPA**: En el contexto educativo anglosajón, GPA (*Grade Point Average*) se refiere al promedio general de calificaciones.

---

## 1.1 Revisión de datos 🔎 [1.2 puntos]

<p align="center">
  <img src="https://media2.giphy.com/media/4FQMuOKR6zQRO/giphy.gif?cid=ecf05e47ii9lhu9tc9tb31d6lafrysp2zyf6u8w3y348mk8t&rid=giphy.gif&ct=g">
</p>


*Don Caguayo*, rector de la Universidad de la Cachaña, les comenta que actualmente la Universidad no tiene una subdirección de análisis de datos, pero que tiene interés en formar una. Es por esto, que se contacta con ud. y su equipo para iniciar de forma exploratoria diversas tareas de análisis y consolidación de datos respectivos al rendimiento de sus alumnos.

En su primera reunión, el rector les comenta que la sección de TI posee una base de datos con más de **1000** filas, en donde cada fila representa un alumno matriculado. Sin embargo, cree fuertemente que existen errores en esta: solo tiene registro de **1000** matriculas. Por este motivo, especula que se han realizado malas prácticas al inscribir dichos datos.


En consecuencia, el rector les solicita a ustedes como tarea inicial que exploren la base de datos y encuentre posibles falencias dentro de sus registros. Para esto, usted debe estar al tanto que las notas (GPA) están en una escala que van del **0 al 100** (porcentaje de logro) y **no es posible que un alumno aparezca más de una vez, ya que las notas son promedios de sus asignaturas**. 

Cualquier alumno que posea un valor diferente a esta escala, debería ser eliminado de la base de datos.


> **Instrucciones**

Implemente la función `analyze_df` que tome un `DataFrame` y que le permita generar diversos análisis que permitan observar estadísticas y anomalías de las diferentes variables que componen este dataset.

**To-Do**
1. [ ] Imprimir un mensaje con las dimensiones del Dataframe. [0.1 puntos]
2. [ ] Imprimir un mensaje con los nombres de las columnas que conforman el DataFrame. [0.1 puntos]
3. [ ] Mostrar los primeros 5, los últimos 5 elementos del DataFrame y realice un muestreo de 5 elementos de forma aleatoria. [0.1 puntos]
4. [ ] Mostrar una descripción rápida de las variables numéricas del DataFrame (utilice un método visto en clases). [0.1 puntos]
5. [ ] Imprimir un mensaje con la cantidad de valores nulos (investigue el método `isna()` y `sum()` de los DataFrames). [0.1 puntos]
6. [ ] Imprimir un mensaje que detalle la cantidad de valores unicos (investigue `nunique()`) . [0.1 puntos]
7. [ ] Imprimir un mensaje con el total de filas que contengan nombres duplicados (investigue `duplicated()` y su parámetro `subset`). [0.1 puntos]
8. [ ] Mostrar las filas que contengan nombres sean duplicados (investigue `duplicated()` y su parámetro `subset`). [0.1 puntos]
9. [ ] A través de `px.histogram(col_name, title="Título").show()` graficar el histograma de cada tipo de nota (`math score`, `reading score`, `writing score`). Investigue cómo funcionan los histogramas si es necesario. [0.2 puntos]
10. [ ] Responda las preguntas en la celda correspondiente. [0.2 puntos]

> **Nota:** Para imprimir utilice `print(...)`. Para mostrar `DataFrames`, utilice `display(...)` ya que este permite mostrar estos elementos como tablas.

> **Nota 2:** Utilice la documentación de [pandas](https://pandas.pydata.org/docs/index.html) como también StackOverflow para resolver cualquier problema o inconveniente.

**Respuesta Código:**

In [5]:
# Primero deberan cargar los datos usando un lector apropiado
df_grades = pd.read_json("students_grades.json")

In [30]:
def analyze_df(df: pd.DataFrame) -> None:
    dimensiones = df.shape
    columnas = df.columns
    primeros_5 = df.head(5)
    ultimos_5 = df.tail(5)
    random_5 = df.sample(5)
    nulos = df.isna().sum()
    unicos = df.nunique().sum()
    duplicados = df.duplicated().sum()
    df_dupli = df[df.duplicated()]
    # lo tenemos que pasar a numero ya que lo esta identificando como texto las variables numericas
    col_names = ["math score", "reading score", "writing score"]
    df[col_names] = df[col_names].apply(pd.to_numeric, errors="coerce")
    descrip_num = df[col_names].describe()

    print("Análisis del dataframe")
    print("===" * 5)
    # 1. Imprimir las dimensiones del dataframe
    print(f"Dimensiones (Filas, Columnas): {dimensiones}")
    print("---" * 10)
    # 2. Imprimir los nombres de las columnas
    print(f"\nColumnas presentes: {list(columnas)}")
    print("---" * 10)
    # 3. Imprimir los primeros 5, ultimos 5 y muestre aleatorio de 5.
    print("Primeras 5 filas")
    display(primeros_5)
    print("Últimas 5 filas")
    display(ultimos_5)
    print("Muestra Aleatoria de 5 filas")
    display(random_5)
    # 4. Descripción de los valores numericos
    print("Descripción de Variables Numericas")
    display(descrip_num)
    print("---" * 10)
    # 5. Cantidad de valores nulos
    print("Valores Nulos por Columna:")
    print(nulos)
    print("---" * 10)
    # 6. Cantidad de valores unico
    print(f"Cantidad de valores únicos: {unicos}")
    print("Cantidad de valores únicos por columna:")
    display(df.nunique())
    print("---" * 10)
    # 7. Total de filas con duplicados
    print(f"Cantidad de filas duplicadas: {duplicados}")
    print("---" * 10)
    # 8. Mostrar dataframe de filas duplicadas
    print("Filas duplicadas:")
    display(df_dupli)
    print("---" * 10)

    # 9. Histograma de cada tipo de nota
    histograma = px.histogram(df, x=col_names, title="Histograma Notas por Tipo")
    histograma.show()

In [31]:
analyze_df(df_grades)

Análisis del dataframe
Dimensiones (Filas, Columnas): (1400, 9)
------------------------------

Columnas presentes: ['names', 'gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']
------------------------------
Primeras 5 filas


,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0
1,Madeline Fuller,female,group C,some high school,standard,none,124.0,142.0,142.0
2,Daniel Rester,male,group E,associate's degree,standard,none,156.0,196.0,193.0
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0
4,Geraldine Hale,female,group A,associate's degree,standard,none,131.0,166.0,166.0


Últimas 5 filas


,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1395,Alexander Dillon,male,group D,associate's degree,standard,none,193.0,142.0,193.0
1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66.0,74.0,81.0
1397,Laurie Carter,female,group B,some high school,standard,completed,54.0,61.0,62.0
1398,Joseph Mccoy,male,group D,some college,free/reduced,none,193.0,196.0,193.0
1399,Amanda Perez,female,group A,high school,standard,completed,68.0,80.0,76.0


Muestra Aleatoria de 5 filas


,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1291,Bonnie Rodriguez,female,group E,high school,standard,completed,74.0,79.0,80.0
620,Richard Taylor,male,group B,associate's degree,standard,none,87.0,85.0,73.0
700,Belinda Tuholski,female,group C,associate's degree,standard,none,91.0,95.0,94.0
1275,Kenneth Webster,male,group E,associate's degree,free/reduced,none,64.0,56.0,52.0
915,Andrew Baker,male,group E,associate's degree,standard,completed,62.0,56.0,53.0


Descripción de Variables Numericas


,math score,reading score,writing score
count,1360.000000,1360.000000,1353.000000
mean,89.538971,93.086029,91.852919
std,47.152422,46.385775,47.043570
min,0.000000,17.000000,10.000000
25%,59.000000,63.000000,62.000000
50%,72.000000,76.000000,75.000000
75%,97.250000,100.000000,100.000000
max,196.000000,196.000000,196.000000


------------------------------
Valores Nulos por Columna:
names                           0
gender                          0
race/ethnicity                  0
parental level of education     0
lunch                           0
test preparation course         0
math score                     40
reading score                  40
writing score                  47
dtype: int64
------------------------------
Cantidad de valores únicos: 1446
Cantidad de valores únicos por columna:


names                          1153
gender                            2
race/ethnicity                    5
parental level of education       6
lunch                             2
test preparation course           2
math score                       96
reading score                    88
writing score                    92
dtype: int64

------------------------------
Cantidad de filas duplicadas: 3
------------------------------
Filas duplicadas:


,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
827,Justin Harris,male,group D,some college,standard,none,40.0,42.0,38.0
900,Anthony Malcomb,male,group C,some college,free/reduced,none,35.0,28.0,27.0
1223,Charles Jackson,male,group E,some high school,standard,none,30.0,26.0,22.0


------------------------------


**Preguntas ❓:**

> ¿Qué anomalías es posible observar de los datos que componen el DataFrame? 

> ¿Existen valores nulos o duplicados? ¿Qué puede interpretar de la distribución de las notas en los histogramas?


**Respuestas 📝:**

```
En primera instancia, se puede notar una inconsistencia en el volumen de datos, ya que hay 1400 filas, numero que supera las 1000 matrículas mencionadas inicialmente por el rector. Esto también se puede ver en la columna "names", que solo cuenta con 1157 valores únicos. Al revisar las primeras 5 filas, las últimas 5 filas del dataframe y la muestra aleatoria de 5 filas, se detectan puntajes sobre 100 lo que evidencia una anomalía, posiblemente en el ingreso de datos.

La cantidad de filas duplicadas es 3, lo que no explica la brecha entre los 1400 registros y los 1157 nombres. Esto nos sugiere que existen múltiples registros para un mismo alumno con datos distintos, más que copias idénticas (duplicados) de las filas.

Estadísticamente, el límite inferior de 0 es consistente, pero el superior de 100 es sobrepasado en todas las materias (math, reading y writing), llegando a un máximo de 196. Por otro lado, ninguna columnas tiene valores nulos, sin embargo, se presentan duplicados llegando a ser el máximo de 3 registros por persona.

En el histograma, se observa una campana de Gauss normal para los puntajes válidos (dentro del rango 0-100), pero luego aparece un salto que comienza desde los 120 y se extiende hasta 193 en el puntaje. Estos registros fuera de rango representan puntajes no reales y pueden considerarse outliers, ya que se alejan de la distribución de la mayoría de los datos y del límite de la escala de puntaje.
```

---

## 1.2 Limpieza de Datos 🫧

<p align="center">
  <img src="https://media3.giphy.com/media/c09yGbnSyaFRS/giphy.gif?cid=ecf05e47d0ejjjnpfj0ywcbwz7zk7sw2rfdpis890gmdpvj2&rid=giphy.gif&ct=g">
</p>


¡Bien! Ya identificaron las anomalías. Ahora es momento de poner manos a la obra y limpiar esos datos. 🧹

En base a lo realizado anteriormente, realice una limpieza del dataset. Asuma los supuestos señalados en la pregunta anterior para limpiar el DataFrame y cree una función que le permita limpiar los datos. Una vez limpiado, compruebe nuevamente los datos con la función creada en la sección 1.1.

**To-Do:**

- [ ] Crear función que permita limpiar el dataset.
  - [ ] Cambiar el nombre de las columnas a snake case (Hint: implementar util `to_snake_case` usando métodos de strings + list/dict comprehension). [0.1 puntos]
  - [ ] Eliminar la palabra `race` de la columna `race/ethnicity` (Hint: `rename`) [0.1 puntos]
  - [ ] Eliminar datos duplicados [0.2 puntos]
  - [ ] Forzar tipos de las columnas con score a float con `pd.to_numeric, errors="coerce")` (Hint: coerce dejará como nulos los valores que no sean floats, importante para el siguiente paso)[0.2 puntos]
  - [ ] Eliminar datos nulos [0.2 puntos]
  - [ ] Eliminar registros con notas anómalas (> 100, < 0) [0.2 puntos]
- [ ] Comprobar que ya no existen anomalías en los datos usando la función de la sección 1.1 (solo imprimir, no justificar). Puede que necesite adaptar la función para usar los nuevos nombres de columnas

**Respuesta:**

In [ ]:
def to_snake_case(s: str) -> str:  # revisar
    c = s.lower().replace(" ", "_")
    return c

In [ ]:
def clean_data(df: pd.DataFrame) -> pd.DataFrame: ...

In [ ]:
df_cleaned = clean_data(df_grades)
df_cleaned

> Utilice la función creada en el punto 1.1 para verificar sus resultados. Adapte los nombres de las columnas con snake_case si es necesario.

**✅ Checkpoint**: Después de la limpieza deberías tener exactamente 1000 filas


---

## 1.3 Creando y Estructurando Datos 📊



<p align="center">
  <img src="https://media4.giphy.com/media/ko7twHhomhk8E/giphy.gif?cid=ecf05e47xmgfz8ftaom8saa4cwktxpb0fkui9yk3nakb4ff1&rid=giphy.gif&ct=g">
</p>

¡Perfecto! Ya tenemos datos limpios y confiables. Ahora Don Caguayo quiere que le ayudemos a generar nuevas columnas y realizar análisis más profundos. 📊

---

### 1.3.1 Transformación de notas a "Nota Chilena" 🇨🇱 [0.5 puntos]

Con todas las notas transformadas, la prestigiosa Universidad De la Cachaña necesita obtener el promedio general (GPA) de cada uno de los alumnos. Para esto se le solicita que calcule el promedio de las tres asignaturas y lo anexe como una nueva columna al DataFrame. 

Cabe señalar que las notas promedio deben ser **redondeadas** al segundo decimal.

**To-Do:**
- [ ] Implementa la función `calculate_average` que dado un dataframe con las notas por alumno, calcula y retorna dos **Series**: una con el promedio de las notas originales (escala 0-100) y otra con el promedio de las notas chilenas. [0.3 puntos]
- [ ] Ejecuta la función y luego, usando indexadores apropiados, agrega las columnas `mean` (promedio escala 0-100) y `mean_cl` (promedio escala chilena) a `df_cleaned`. [Sin puntos]

**Respuesta Código:**

In [ ]:
# En esta celda implementa la operación solicitada
def to_chilean_grade(df: pd.DataFrame, columna: str) -> tuple[pd.Series, pd.Series]: ...

In [ ]:
# En esta celda ejecuta la función y luego usa indexadores para agregar las nuevas columnas al dataframe limpio

---

### 1.3.2 Promedios 📋 [0.3 puntos]

Con todas las notas transformadas, la prestigiosa Universidad De la Cachaña necesita obtener el promedio general (GPA) de cada uno de los alumnos. Para esto se le solicita que calcule el promedio de las tres asignaturas y lo anexe como una nueva columna al DataFrame. 

Cabe señalar que las notas promedio deben ser **redondeadas** al segundo decimal.

**To-Do:**
- [ ] Implementa la función `calculate_average` que dado un dataframe con las notas por alumno, calcula y retorna dos **Series**: una con el promedio de las notas originales (escala 0-100) y otra con el promedio de las notas chilenas.
- [ ] Ejecuta la función y luego, usando indexadores apropiados, agrega las columnas `mean` (promedio escala 0-100) y `mean_cl` (promedio escala chilena) a `df_cleaned`.


**Respuesta:**

In [ ]:
# En esta celda implementa la operación solicitada
def calculate_average(df: pd.DataFrame) -> pd.Series: ...

In [ ]:
# En esta celda ejecuta la función y luego usa indexadores para agregar la nueva columna al dataframe limpio

---

### 1.3.3 Rankings 📶 [0.4 puntos]

¡Excelente trabajo calculando los promedios! Ahora Don Caguayo quiere saber quiénes son los estudiantes top y generar un ranking general.

**To-Do:**
- [ ] Implementa la función `rank_students` que dado un dataframe con las notas por alumno, obtiene una **Serie** con el ranking de alumnos, de mejor a peor nota (usando el promedio chileno `mean_cl`).
- [ ] Ejecuta la función y luego, usando indexadores apropiados, agrega la columna `rank` al `df_cleaned`.


In [ ]:
# En esta celda implementa la operación solicitada
def rank_students(df: pd.DataFrame) -> pd.Series: ...

In [ ]:
# En esta celda ejecuta la función y luego usa indexadores para agregar la nueva columna al dataframe limpio

**Preguntas ❓:**


1. ¿Qué pasa si hay alumnos con el mismo promedio? 
2. ¿Cómo se debería manejar el ranking en ese caso? 
3. ¿Qué parámetro deberían configurar? 
 
4. ¿Cuál es el comportamiento por defecto?

**Respuestas 📝:**

```
Escriba aquí las respuestas a las preguntas
```

---

### 1.3.4 Reprobados y Destacados 🏅

Contentos con su desempeño, la Universidad les solicita que identifiquen a los alumnos que han reprobado el año y a los que han tenido un desempeño destacado.

Para esto se considerará que:
- Un alumno ha **reprobado** cuando el promedio de notas chilenas (`mean_cl`) es inferior a 4.0
- Un alumno es **destacado** si posee notas chilenas superiores a 6.0 en `math_score_cl` y superiores a 6.3 en `reading_score_cl` y `writing_score_cl`


Cree las siguientes funciones:

1. [ ] `extract_failing` que retorne un DataFrame con solamente los alumnos que han reprobado en la prestigiosa universidad. [0.3 puntos]
2. [ ]  `sort_top` que extraiga los n (parametrizable) alumnos destacados, ordenados de mayor a menor promedio. [0.3 puntos]

**Respuesta:**

In [ ]:
def extract_failing(df: pd.DataFrame) -> pd.DataFrame: ...


df_failing = extract_failing(df_cleaned)

In [ ]:
def sort_top(df: pd.DataFrame, n: int) -> pd.DataFrame: ...


df_top_students = sort_top(df_cleaned, n=10)

---

### 1.3.5 Padres Helicóptero 👨‍👩‍👧

Algunos padres (extremadamente entrometidos) preocupados por el desempeño de sus hijos, desean saber si estos han aprobado o no el año. Como la tarea de buscar a mano cada uno de estos alumnos en el `DataFrame` resulta demasiado tedioso, el rector le solicita crear una función de consulta. 

Cree una función que:

1. Reciba el `DataFrame` y una lista con nombres de alumnos
2. Extraiga las notas chilenas de matemáticas, escritura, lectura y promedio general (`mean_cl`) de los alumnos listados en `student_list` [0.3 puntos]
3. Genere una nueva columna transitoria `is_failing` (**asegurarse de no agregarla al dataframe original**) cuyo valor sea `True` si el alumno está reprobando o `False` en caso contrario [0.3 puntos]
4. Ordene por promedio chileno, de mayor a menor [0.2 puntos]
5. Reinicie el índice para que este comience desde 0 [0.2 puntos]


**Hint:** Puede serle de utilidad utilizar `isin()`. Recuerde además usar una copia del dataframe original para no modificarlo con la nueva columna.

**Respuesta:**

In [ ]:
def query_students(df: pd.DataFrame, student_list: list[str]) -> pd.DataFrame: ...

In [ ]:
student_list = [
    "Lucille Stanphill",
    "Marcus Mcfarland",
    "Matthew Freeman",
    "Dana Mojica",
    "Paul Hyder",
    "Jeffrey Korn",
    "Robert Strain",
    "Ronald Jett",
    "Lorena Reed",
    "Hazel Posey",
]

df_query = query_students(df_cleaned, student_list)
df_query

---

### 1.3.6 Categorías de Rendimiento 📊

El rector, intrigado por saber si existe una relación entre el nivel educacional de los padres y las notas de sus hijos, les plantea estudiar dicha relación mediante categorización de los datos. 

Para esto, se les solicita que implementen la función `get_categories`, donde se generen dos series con diferentes tipos de categorización a partir de los promedios chilenos (`mean_cl`):

- Una con `pd.cut` con las labels `["B1", "B2", "B3", "B4", "B5"]` [0.2 Puntos]
- Otra con `pd.qcut`, con las labels `["Q1", "Q2", "Q3", "Q4", "Q5"]` [0.2 Puntos]

La función debe retornar una tupla con ambas series. Después, usando indexadores apropiados, agreguen a `df_cleaned` las columnas `cut_cl` y `qcut_cl`.

**Respuesta:**

In [ ]:
# En esta celda implementa la operación solicitada
def get_categories(df: pd.DataFrame) -> tuple[pd.Series, pd.Series]: ...

Hecho esto, grafique a través de un scatter plot el nivel educacional de los padres v/s el promedio chileno de los alumnos. Utilice los quintiles generados anteriormente (use la columna `qcut_cl`) para colorear los puntos y mostrar en qué quintil se encuentra cada dato.

**Pregunta: ❓** [0.3 Puntos]

> - ¿Qué diferencias hay entre las categorías generadas por `cut` y `qcut` (en términos conceptuales rangos-percentiles)?


**Respuesta 📝:**

```
Escriba aquí las respuestas a las preguntas
```

In [ ]:
# Código para graficar
# Nota: asegúrese de que la columna qcut_cl esté creada antes de ejecutar esto

fig = px.scatter(
    df_cleaned.sort_values(by="mean_cl"),
    x="mean_cl",
    y="parental_level_of_education",
    hover_data=["gender"],
    color="qcut_cl",
    title="Promedio por Nivel de Educación de los Padres",
    labels={"mean_cl": "Promedio (Escala Chilena)", "parental_level_of_education": "Nivel Educacional de los Padres"},
    color_discrete_sequence=["tomato", "orange", "yellow", "greenyellow", "green"],
)

**Pregunta: ❓** [0.3 Puntos]

> - ¿Es posible visualizar alguna tendencia en el gráfico?


**Respuesta 📝:**

```
Escriba aquí las respuestas a las preguntas
```

---

# Conclusión

Cualquier duda del laboratorio, no duden en contactarnos por mail o U-cursos.

<p align="center">
  <img src="https://gifdb.com/images/high/orange-cat-cat-walking-with-two-legs-xlgf7qx4i24da74f.gif" width="400">
</p>